services:
  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    container_name: searxng
    ports:
      - "8080:8080"
    volumes:
      - searxng-data:/etc/searxng
      - ./settings.yml:/etc/searxng/settings.yml
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
      - SEARXNG_SECRET=${SEARXNG_SECRET}

volumes:
  searxng-data:
